version: "3.3"

services:
  vscode:
    image: "codercom/code-server"
    container_name: "vscode-server"
    restart: always
    environment:
      - PASSWORD=password  # Replace with your desired password
    ports:
      - 9090:8080
    volumes:
      - "/persist/code:/home/coder/project"
    labels:
      # HTTP configuration
      - "traefik.enable=true"
#      - "traefik.http.routers.vscode-http.rule=Host(`vscode.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.vscode-http.entrypoints=web"
      - "traefik.http.services.vscode-http.loadbalancer.server.port=8080"
      - "traefik.http.routers.vscode-http.rule=Host(`vscode.rutvik2611.com`)"

      # HTTPS configuration
#      - "traefik.http.routers.vscode-https.rule=Host(`vscode.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.vscode-https.rule=Host(`vscode.rutvik2611.com`)"
      - "traefik.http.routers.vscode-https.entrypoints=websecure"
      - "traefik.http.routers.vscode-https.tls.certresolver=myresolver"
      - "traefik.http.services.vscode-https.loadbalancer.server.port=8080"

    networks:
      - backboneNetwork

networks:
  backboneNetwork:
    external: true
