version: "3.3"

services:
  vscode:
    image: codercom/code-server
    container_name: vscode-server
    restart: always
    environment:
      - PASSWORD=password  # Replace with your desired password
    volumes:
      - "./persist/code:/home/coder/project"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      # HTTPS router
      - "traefik.http.routers.vscode-secure.rule=Host(`vscode.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.vscode-secure.entrypoints=websecure"
      - "traefik.http.routers.vscode-secure.tls.certresolver=myresolver"
      - "traefik.http.services.vscode-secure.loadbalancer.server.port=8080"
      # Middleware for redirecting HTTP to HTTPS
#      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    user: "root"
    networks:
      - backboneNetwork
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: always
    environment:
      - PUID=1000  # Replace with your user ID
      - PGID=1000  # Replace with your group ID
      - TZ=Etc/UTC  # Replace with your timezone
    volumes:
      - "./persist/jellyfin/config:/config"
      - "./persist/jellyfin/cache:/cache"
      - "./persist/qbittorrent/downloads:/media"
    labels:
      - "traefik.enable=true"
      # HTTPS router
      - "traefik.http.routers.jellyfin-secure.rule=Host(`jellyfin.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.jellyfin-secure.entrypoints=websecure"
      - "traefik.http.routers.jellyfin-secure.tls.certresolver=myresolver"
      - "traefik.http.services.jellyfin-secure.loadbalancer.server.port=8096"
    networks:
      - backboneNetwork

networks:
  backboneNetwork:
    external: true
