version: "3.3"

services:
  handbrake:
    image: jlesage/handbrake
    container_name: handbrake
    restart: always
#    ports:
#      - "5800:5800"
    volumes:
      - "/app/development/handbrake:/config:rw"
      - "/home/user:/storage:ro"
      - "/app/development/persist/qbittorrent/downloads:/watch:rw"
      - "/app/development/persist/qbittorrent/downloads/handbreak/:/output:rw"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.handbrake.rule=Host(`handbrake.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.handbrake.entrypoints=websecure"
      - "traefik.http.routers.handbrake.tls.certresolver=myresolver"
      - "traefik.http.services.handbrake.loadbalancer.server.port=5800"
      # Middleware for redirecting HTTP to HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.handbrake-secure.rule=Host(`handbrake.${MAIN_DOMAIN}`)"
      - "traefik.http.routers.handbrake-secure.entrypoints=web"
      - "traefik.http.routers.handbrake-secure.middlewares=redirect-to-https"
    networks:
      - backboneNetwork

networks:
  backboneNetwork:
    external: true
